# Generated by Django 3.2.3 on 2021-05-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DialyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=400)),
                ('positiveSentiment', models.IntegerField(default=0)),
                ('negativeSentiment', models.IntegerField(default=0)),
                ('nutralSentiment', models.IntegerField(default=0)),
                ('mixedSentiment', models.IntegerField(default=0)),
                ('isDeleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
