# Generated by Django 3.2.2 on 2021-05-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialy_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialymodel',
            name='mixedSentiment',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dialymodel',
            name='negativeSentiment',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dialymodel',
            name='nutralSentiment',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dialymodel',
            name='positiveSentiment',
            field=models.FloatField(default=0),
        ),
    ]
